endpoint: "wss://westend-rpc.polkadot.io"
port: 3000
logLevel: info
validators:
  - name: PARITY WESTEND VALIDATOR 2
    address: 5GYaYNVq6e855t5hVCyk4Wuqssaf6ADTrvdPZ3QXyHvFXTip
  - name: PARITY WESTEND VALIDATOR 8
    address: 5FZoQhgUCmqBxnkHX7jCqThScS2xQWiwiF61msg63CFL3Y8f
