endpoint: "wss://kusama-rpc.polkadot.io/"
port: 3000
logLevel: info
validators:
  #- name: test
  #  address: Gt6HqWBhdu4Sy1u8ASTbS1qf2Ac5gwdegwr8tWN8saMxPt5
  #- name: test-stake-fish
  #  address: FHfishKQzf3CCWvNDJRCEYTH3HD1eSYa4gBCC35iFznpvus
  - name: kusama-retail-sf-01
    address: FHfishKQzf3CCWvNDJRCEYTH3HD1eSYa4gBCC35iFznpvus
  - name: kusama-retail-sf-02
    address: EfishAJ87FJJgudobhuWmZx96JawQdqKthJBZMLh5oa9f1p
  - name: kusama-retail-sf-03
    address: EVfishUSWF6jePB9D5LtKLZQFpvTP8FYa9KkwJ4htzLLFMD
  - name: kusama-retail-sf-04
    address: EPfishGxTCDjMhMDsmtS4pzxZz1c2aXc1UmDGx14BuPYURs
  - name: kusama-retail-sf-05
    address: DifishR4auphofhzxsy2aupgYo4NaUECH7qgt71CgiB2o6P
  - name: kusama-retail-sf-06
    address: J1fishfH94nFZLNScHgC2HorWpFD2xdPxd96wtTCHLvKxfa
  - name: kusama-retail-sf-07
    address: HEfishe6tVbrbq3jFXvT6hfMZGfSy3kaNpkxrx2vpewwP3R
  - name: kusama-retail-sf-08
    address: DdfishRsE4HPENgvmbz1fjc2TtHe7nQrBzMyVGQSAweDd2y
  - name: kusama-retail-sf-09
    address: Efishjj6mrTWVjwFoxtMmHH3mX6tRNnPKsSfQeCLZSv3jAE
  - name: kusama-retail-sf-10
    address: JEfishiSg6Tua9hofx9ee5kVS38U1LxZiEXcQFTcU87ZkJ3
  - name: kusama-retail-sf-11
    address: Fefish31YMdGVrLYS2kHEosQwwYUN8XfTb9kpL4WrwcWcvG
  - name: kusama-retail-sf-12
    address: DfishSgV6wCW81RTtq9orBHxqirFwxa8sUeBv2Tcff9uYG6
  - name: kusama-retail-sf-13
    address: Cfish3zJiFnTvR9jscCap7imeA9ep3cH1wZfcZwAp2gdZHo
  - name: kusama-retail-sf-14
    address: DfishsttJkwkCqsFVgE9fp9HW8DyX397JgAWM34YrstpUfP
  - name: kusama-retail-sf-15
    address: DfishNKYfnkc87TQxBJZrHTfQXW7dfwFyxZ6YVFYQmFjY8u
  - name: kusama-retail-sf-16
    address: HCfishjDeXFWL11T15bgxb4PHWZtGvbdtyewPkQ1fme2QPC
  - name: kusama-retail-sf-17
    address: GkfishY1tY2LzVwq9vQVoRE8SUwtiiETZW7jsjyAjM21rVb
  - name: kusama-retail-sf-18
    address: EfishhTN91iskotwac8y1moSkqSNRME2HEytVv7YTEQx9iF
  - name: kusama-retail-sf-19
    address: G7fishX3fcHiDPNxAboobcgGEfW4YPfofwqzyDvBAstoHzo
  - name: kusama-retail-sf-20
    address: DwfishqurnJ21kwbMRboqvi2Xz8xHmvanpd61LNsaEF2tRX
  - name: kusama-enterprise-sf-21
    address: FfishQTfiFe7GbNBYBZoeeBYNQmB7xN4ikBWzA8ev6fj1xF
  - name: kusama-enterprise-sf-22
    address: EfishjPfGa53ioSm1YcmQb7PhGBTddDRuSD3jzpiRHUr7Hf
  - name: kusama-enterprise-sf-23
    address: DfishNgWAFp4ckjHzzFQjuF1Wn6UGQBopXnSRj46siaHZuu
  - name: kusama-enterprise-sf-24
    address: Ffish42GSqr9r9yZXq1vmcFeGasmsJ1d7SFihhjawYZwX3i
  - name: kusama-enterprise-sf-25
    address: FfishqSz2ZWw7PpSdryh3f5abgb9eByvdQHkyLQw4AKtNMQ
  - name: kusama-enterprise-sf-26
    address: Cfish1W4QKzegu7CN5Lnd6CbkFL7qpq5QgN6v1m4udCveLZ
  - name: kusama-enterprise-sf-27
    address: DfishveZoxSRNRb8FtyS7ignbw6cr32eCY2w6ctLDRM1NQz
  - name: kusama-enterprise-sf-28
    address: EfishK8YrvrHg9M9vxzXE3YX8Vxc64fbBYFoMtK3QYCFPwv
  - name: kusama-enterprise-sf-29
    address: Efishk3rm2i3acC8sM8z1zqvu2GLbtR9DGoD96bxzciuSr1
  - name: kusama-enterprise-sf-30
    address: EfishySsr7gnP6HKH9U9JgiVj6hHhZb9hUoTD95HCts1xvo
  - name: kusama-enterprise-sf-31
    address: HZfishRkY39sJDez5We9yYkf1CgxSSUaLmkpT7gQQaaM7tW
  - name: kusama-enterprise-sf-32
    address: FfishUaexcMUqiPjM6DsBtCDuKJP4hDuVYyGochBhJkc2FL
  - name: kusama-enterprise-sf-33
    address: Cfishgn1Npz6KJdWJJ54AF1vqiuR4qsVdHdVcV2aZHPR5gu
  - name: kusama-enterprise-sf-34
    address: EfishLWoiTZntBuQbAToMsD7aXMugTVoxRDdea8SqTXgMSz
  - name: kusama-enterprise-sf-35
    address: EkfishCaWGYRt77CXMEw1Be5YYsGpjjuPQjZYNh8wacbH2G
  - name: kusama-enterprise-sf-36
    address: DJfish8d6MUNQYbzZWjeLjmeQgdBrf7RruMAn8euZMbKMAv
  - name: kusama-enterprise-sf-37
    address: EifishhM5zhCbgEHZnW3apgtBSkLubiKb7g6fc2L7U7x35P
  - name: kusama-enterprise-sf-38
    address: FfishAjHw23WbEBM3CCWTXVDLgaS8YJ7LAom9GeHDoPQmF8
  - name: kusama-enterprise-sf-39
    address: Efishf12fdhAMKSQVEzN1Li7oZGCy68ZJyh3CkxS84jMadj
  - name: kusama-enterprise-sf-40
    address: EfishsfPtPLiwZo2jiGZ1ZPMy1cMsNptoXiTfn2uDeDfY64
